In [1]:
import torch

In [2]:
# Initialization Tensor

In [3]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]]) # list in a list
my_tensor

tensor([[1, 2, 4],
        [4, 5, 6]])

In [4]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]],dtype = torch.float32) # list in a list
my_tensor

tensor([[1., 2., 4.],
        [4., 5., 6.]])

In [5]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]],dtype = torch.float32, device = 'cuda') # list in a list
my_tensor

AssertionError: Torch not compiled with CUDA enabled

In [6]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]],dtype = torch.float32, device = 'cpu') # 'cpu' is default
my_tensor

tensor([[1., 2., 4.],
        [4., 5., 6.]])

In [7]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]],dtype = torch.float32, device = 'cpu', requires_grad = True) # 'cpu' is default
my_tensor

tensor([[1., 2., 4.],
        [4., 5., 6.]], requires_grad=True)

In [8]:
device = 'cuda'  if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [9]:
my_tensor = torch.tensor([[1,2,4],[4,5,6]],dtype = torch.float32, device = device, requires_grad = True) # 'cpu' is default
my_tensor

tensor([[1., 2., 4.],
        [4., 5., 6.]], requires_grad=True)

In [13]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
cpu
torch.Size([2, 3])
True


In [ ]:
# other common initialization method

In [15]:
x = torch.empty(size=(3,3)) # uninitialized data, can be zeros or cannot be zeros
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x = torch.rand((3,3)) # uniform distribution b/w 0 to 1
x

tensor([[0.1134, 0.3089, 0.9904],
        [0.4130, 0.8034, 0.1326],
        [0.6700, 0.9579, 0.3160]])

In [18]:
x  = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
x = torch.eye(3,3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
x = torch.arange(start=0, end = 5, step=1) # non-inclusive of the 'end' value
x

tensor([0, 1, 2, 3, 4])

In [23]:
x = torch.linspace(start = 0.1, end = 1, steps = 10) # here it is stePS not steP # inclusive of the 'end'
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [24]:
x = torch.empty(size = (1,5)).normal_(mean = 0, std =1)
x

tensor([[-0.6716, -0.0896,  0.3804, -0.4346, -0.0035]])

In [27]:
x = torch.empty(size = (1,5)).uniform_(0,1)
x

tensor([[0.9757, 0.0129, 0.7058, 0.2192, 0.4651]])

In [32]:
torch.ones(3)

tensor([1., 1., 1.])

In [28]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [34]:
x = torch.diag(torch.ones(3,3))
x

tensor([1., 1., 1.])

In [29]:
x = torch.diag(torch.rand((3,3)))
x

tensor([0.4554, 0.1105, 0.7813])

In [33]:
a = torch.rand((3,3))
x = torch.diag(a)
print(a)
print(x)

tensor([0.7784, 0.8411, 0.6857])
tensor([[0.7784, 0.0000, 0.0000],
        [0.0000, 0.8411, 0.0000],
        [0.0000, 0.0000, 0.6857]])


In [35]:
# convert tensor types

In [44]:
my_tensor = torch.arange(4)
#my_tensor = torch.arange(start = -2, end = 6, step=1)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.bool())
print(my_tensor.short()) # convert to int.16
print(my_tensor.long())  # convert to int64 IMPORTANT
print(my_tensor.half()) # float16
print(my_tensor.float()) # float32 IMPORTANT
print(my_tensor.double()) # float 64 

tensor([0, 1, 2, 3])
torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [46]:
# numpy to tensor

In [49]:
import numpy as np
np_array = np.zeros((5,5))
my_tensor = torch.from_numpy(np_array)
print(my_tensor)

# to get numpy array back
my_array_back = my_tensor.numpy()
print(my_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
