In [1]:
import torch
import numpy as np

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [82]:
x = torch.tensor([1,2,3])
y = torch.tensor([7,8,9])


In [4]:
# Addition

In [5]:
z1 = torch.empty(3)
print(z1)
torch.add(x,y, out = z1)
print(z1)

tensor([0., 0., 0.])
tensor([ 8., 10., 12.])


In [6]:
z2 = torch.add(x,y)
z2

tensor([ 8, 10, 12])

In [7]:
z3 = x+y # preferred
z2

tensor([ 8, 10, 12])

In [8]:
# subtraction

In [9]:
z = x-y
z

tensor([-6, -6, -6])

In [11]:
# division

In [13]:
z = torch.true_divide(x,y) # element-wise division
z

tensor([0.1429, 0.2500, 0.3333])

In [18]:
# inplace operations

In [16]:
t = torch.zeros(3)
t.add_(x) # whenever an operation has '_' at end => inplace operation
print(t)

tensor([1., 2., 3.])


In [17]:
t +=x
t

tensor([2., 4., 6.])

In [19]:
# exponentiation

In [20]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [21]:
z = x**2
z

tensor([1, 4, 9])

In [22]:
# simple comparisons

In [23]:
z = x>0 # element-wise comparison
z

tensor([True, True, True])

In [24]:
z = x<0
z

tensor([False, False, False])

In [25]:
# matrix multiplication

In [27]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2)
x3

tensor([[1.2751, 0.6750, 1.3783],
        [2.0792, 1.1310, 1.8612]])

In [28]:
x3 = x1.mm(x2)
x3

tensor([[1.2751, 0.6750, 1.3783],
        [2.0792, 1.1310, 1.8612]])

In [29]:
# matrix exponentiation

In [35]:
x4 = torch.rand((5,5))
print(x4)
print(x4.matrix_power(3))

tensor([[0.4116, 0.2395, 0.3212, 0.0805, 0.2014],
        [0.4694, 0.7767, 0.9586, 0.6860, 0.7668],
        [0.7182, 0.2247, 0.1865, 0.0579, 0.9797],
        [0.0719, 0.1221, 0.2785, 0.4550, 0.3177],
        [0.9277, 0.5323, 0.2596, 0.9234, 0.2200]])
tensor([[1.5046, 1.0484, 1.0644, 1.2113, 1.2741],
        [4.5340, 3.1887, 3.2635, 3.8331, 3.8962],
        [2.3296, 1.7591, 1.9960, 1.9915, 2.2587],
        [1.3244, 0.9383, 0.9783, 1.1722, 1.1465],
        [2.9052, 2.0069, 2.0631, 2.3797, 2.6793]])


In [36]:
# element-wise multiplication

In [37]:
z = x* y
z

tensor([ 7, 16, 27])

In [39]:
# dot-product

In [40]:
z = torch.dot(x,y)
z

tensor(50)

In [41]:
# batch matrix-multiplication

In [45]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch,n,m))
print(tensor1.shape)
tensor2 = torch.rand((batch,m,p))
print(tensor2.shape)
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm.shape)

torch.Size([32, 10, 20])
torch.Size([32, 20, 30])
torch.Size([32, 10, 30])


In [46]:
# broadcasting

In [47]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1-x2
z

tensor([[-0.1895, -0.0162, -0.1473,  0.2020, -0.2481],
        [-0.0444,  0.1305, -0.5062,  0.1264,  0.5217],
        [-0.0256, -0.3652, -0.7146,  0.3004,  0.1781],
        [ 0.3919,  0.3545, -0.1336,  0.3207, -0.3675],
        [ 0.1986,  0.1484, -0.1641,  0.3661,  0.1768]])

In [50]:
z = x1**x2 # element-wise exponentiation to x2
z

tensor([[0.5694, 0.7211, 0.7610, 0.8145, 0.4752],
        [0.6861, 0.8248, 0.4210, 0.7724, 0.9726],
        [0.7000, 0.4154, 0.2057, 0.8646, 0.8048],
        [0.9655, 0.9679, 0.7735, 0.8743, 0.2796],
        [0.8512, 0.8369, 0.7456, 0.8955, 0.8041]])

In [51]:
# other useful tensor operations

In [52]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [83]:
max_val, max_ind = torch.max(x, dim = 0)
print(max_val, max_ind)

max_val, max_ind = x.max( dim = 0)
print(max_val, max_ind)

tensor(3) tensor(2)
tensor(3) tensor(2)


In [55]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [56]:
z = torch.argmax(x, dim=0)
z

tensor(2)

In [57]:
z = torch.argmin(x, dim=0)
z

tensor(0)

In [58]:
mean_x = torch.mean(x.float(), dim=0) # pytorch requires it to be float for mean calculation

In [63]:

print(x.dtype)
print((x.float()).dtype)

torch.int64
torch.float32


In [64]:
z = torch.eq(x,y) # check which elements are equal
z

tensor([False, False, False])

In [65]:
torch.sort(y,dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([0, 1, 2]))

In [66]:
torch.sort(y,dim=0, descending=True)

torch.return_types.sort(
values=tensor([9, 8, 7]),
indices=tensor([2, 1, 0]))

In [67]:
sorted_y, indices = torch.sort(y,dim=0, descending=True)
print(sorted_y, indices)

tensor([9, 8, 7]) tensor([2, 1, 0])


In [68]:
z = torch.clamp(x, min=0, max = 10) # set min = 0 if elements are less than 0 and 10 if elements are more than 10
z

tensor([1, 2, 3])

In [74]:
# Relu
z = torch.clamp(x, min=0)
z

tensor([1, 2, 3])

In [80]:
x = torch.tensor([1,0,1,1,1,1], dtype = torch.bool)
print(x)
z = torch.any(x)
print(z)
z = torch.all(x)
print(z)

tensor([ True, False,  True,  True,  True,  True])
tensor(True)
tensor(False)
