In [1]:
import torch
import numpy as np

In [2]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0])# first sample features # same as x[0,:]
print(x[0].shape) 


tensor([0.0743, 0.3910, 0.1053, 0.4591, 0.1448, 0.8960, 0.9152, 0.0210, 0.9539,
        0.2030, 0.6312, 0.5912, 0.3944, 0.7924, 0.0281, 0.7313, 0.0046, 0.1368,
        0.9471, 0.7864, 0.7030, 0.1035, 0.8220, 0.2977, 0.6877])
torch.Size([25])


In [3]:
print(x[:,0])# first feature of all 10 examples

tensor([0.0743, 0.1899, 0.5762, 0.8538, 0.7379, 0.5125, 0.7871, 0.3682, 0.4882,
        0.9312])


In [4]:
print(x[2,:10]) # 3rd sample first 10 features

tensor([0.5762, 0.9851, 0.3300, 0.3487, 0.7826, 0.9337, 0.0040, 0.3921, 0.8291,
        0.1683])


In [5]:
x[0,0] = 100 # to change

In [6]:
# fancy indexing

In [8]:
x = torch.arange(10)
print(x)
indices = [2,5,8]
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [10]:
x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols]) # picks out 2nd row 5th column and then, 1st row and 1st column

tensor([[0.0192, 0.4479, 0.3799, 0.7579, 0.4431],
        [0.7117, 0.0163, 0.6514, 0.5738, 0.2574],
        [0.4150, 0.3179, 0.9449, 0.8133, 0.6602]])
tensor([0.2574, 0.0192])


In [11]:
# advanced indexing

In [12]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print(x[(x<2)| (x>8)]) # pick elements less than 2 or greater than 8

tensor([0, 1, 9])


In [15]:
print(x[(x<2)& (x>8)]) # no solution -> empty tensor

tensor([], dtype=torch.int64)


In [16]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [17]:
# useful operations

In [19]:
print(torch.where(x>5,x,x*2)) # find where x>5, if x>5 then remain same, if x!>5 then multiply by 2

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [20]:
print(torch.tensor([0,0,1,2,3,4,4,2]).unique())

tensor([0, 1, 2, 3, 4])


In [22]:
print(x.ndimension())

1


In [25]:
print(x.ndim)

1


In [28]:
x = torch.rand([5,5,5])
print(x.ndimension())
print(x.ndim)
print(x.numel()) # count number of elements in x

3
3
125
