In [1]:
import torch

In [2]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
x_new = x.view(3,3) # 'view' act on contiguous tensor
x_new

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [13]:
y = x_new.t() # transpose
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [16]:
y.view(9) # won't work

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [19]:
y.contiguous().view(9) # will work

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [14]:
x_new = x.reshape(3,3) # does not matter when using 'reshape'
x_new

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [15]:
# reshape is best but might be more memory consuming if you dont know how to use 'view'

In [11]:
y = x_new.t() # transpose
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [21]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2), dim = 0).shape)
print(torch.cat((x1,x2), dim = 1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [24]:
# unroll or flatten

In [26]:

z = x1.view(-1)
print(z.shape)
z

torch.Size([10])


tensor([0.8021, 0.5558, 0.5786, 0.7668, 0.4171, 0.3030, 0.8171, 0.9214, 0.1059,
        0.9668])

In [27]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch,-1)
print(z.shape)


torch.Size([64, 10])


In [28]:
# switch the axis

In [29]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [37]:
x = torch.arange(10)
print(x.shape)              #[10]
print(x.unsqueeze(0).shape) # [1,10]
print(x.unsqueeze(1).shape) 


torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])


In [38]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 10])


In [39]:
z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
